package sandbox

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os/exec"
	"time"

	"github.com/jedwards1230/agent-sdk-go/loop"
	"github.com/jedwards1230/agent-sdk-go/provider"
	"github.com/jedwards1230/agent-sdk-go/tool"
)

// containedBashDefaultTimeout is the internal timeout applied when a bash
// call omits timeout_ms — it mirrors the SDK builtin bash tool's default.
const containedBashDefaultTimeout = 120_000 * time.Millisecond

// containedBashMaxTimeout caps timeout_ms regardless of what the model
// requests — it mirrors the SDK builtin bash tool's cap.
const containedBashMaxTimeout = 600_000 * time.Millisecond

// WrapRegistry returns the builtin tool set rooted at cwd with bash executed
// inside c when c.Available(); on an unavailable (or nil) Container it
// returns the plain builtins unchanged — those bash calls are gated to "ask"
// by the guard instead of running contained, since [Container.CanContain]
// also reports false once Available() is false. It is the registry gofer
// injects via runner.Options.Tools.
//
// Only bash's execution is wrapped: Specs() is untouched, so the model still
// sees the same bash name, description, and JSON schema the plain builtin
// advertises.
//
// extra are gofer's OWN tools, registered alongside the builtins — they appear
// in Specs() and resolve through Get exactly as a builtin does, and they are
// never sandbox-wrapped (only bash is). It is the seam gofer-authored tools
// like internal/decision's ask_user enter the session's tool surface through.
// A name colliding with a builtin panics, matching tool.NewRegistry: the tool
// set is fixed at wiring time, so a collision is a build-the-supervisor bug, not
// a runtime condition.
func WrapRegistry(cwd string, c Container, extra ...tool.Tool) loop.ToolRegistry {
	base := loop.FromRegistry(tool.NewRegistry(append(tool.Builtins(cwd), extra...)...))
	if c == nil || !c.Available() {
		return base
	}
	return containedRegistry{
		base: base,
		bash: &containedBash{container: c, workdir: cwd},
	}
}

// containedRegistry delegates every tool except bash to base, and bash to a
// contained variant that shells out through [Container.WrapCommand]. Specs()
// is passed through unchanged.
type containedRegistry struct {
	base loop.ToolRegistry
	bash loop.Tool
}

func (r containedRegistry) Get(name string) (loop.Tool, bool) {
	if name == "bash" {
		return r.bash, true
	}
	return r.base.Get(name)
}

func (r containedRegistry) Specs() []provider.ToolSpec { return r.base.Specs() }

// containedBash is the bash [loop.Tool] variant WrapRegistry wires in when
// the Container is available: instead of exec'ing the model's command
// directly, it asks the Container to wrap it and runs the resulting argv.
type containedBash struct {
	container Container
	workdir   string
}

// containedBashInput is the decoded shape of containedBash's Run argument —
// it mirrors the SDK builtin bash tool's input schema exactly, since Specs()
// still advertises that schema to the model.
type containedBashInput struct {
	Command   string `json:"command"`
	TimeoutMS int    `json:"timeout_ms"`
}

// Run implements [loop.Tool]. It never shells out to command directly —
// every exec happens through the argv the Container's WrapCommand returns.
func (b *containedBash) Run(ctx context.Context, input json.RawMessage) (loop.ToolResult, error) {
	var in containedBashInput
	if len(input) > 0 {
		if err := json.Unmarshal(input, &in); err != nil {
			return loop.ToolResult{}, fmt.Errorf("sandbox: contained bash: decode input: %w", err)
		}
	}
	if in.Command == "" {
		return loop.ToolResult{}, fmt.Errorf("sandbox: contained bash: command is required")
	}

	argv, ok := b.container.WrapCommand(in.Command, b.workdir)
	if !ok || len(argv) == 0 {
		return loop.ToolResult{
			Content: "sandbox: this command cannot run contained on this host",
			IsError: true,
		}, nil
	}

	timeout := containedBashDefaultTimeout
	if in.TimeoutMS > 0 {
		timeout = time.Duration(in.TimeoutMS) * time.Millisecond
		if timeout > containedBashMaxTimeout {
			timeout = containedBashMaxTimeout
		}
	}
	runCtx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()

	cmd := exec.CommandContext(runCtx, argv[0], argv[1:]...) // #nosec G204 -- argv is generated by the sandbox backend (profile_seatbelt.go / profile_bwrap.go), not passed through from raw model input
	cmd.Dir = b.workdir
	var buf bytes.Buffer
	cmd.Stdout = &buf
	cmd.Stderr = &buf

	runErr := cmd.Run()

	// The external ctx being cancelled always aborts the call, even if the
	// internal timeout also expired at the same moment.
	if ctx.Err() != nil {
		return loop.ToolResult{}, ctx.Err()
	}

	content := buf.String()
	switch {
	case runCtx.Err() != nil:
		content += fmt.Sprintf("\n… command timed out after %s", timeout)
		return loop.ToolResult{Content: content, IsError: true}, nil
	case cmd.ProcessState != nil:
		exitCode := cmd.ProcessState.ExitCode()
		if exitCode != 0 {
			content += fmt.Sprintf("\n[exit %d]", exitCode)
		}
		return loop.ToolResult{Content: content, IsError: exitCode != 0}, nil
	case runErr != nil:
		content += fmt.Sprintf("\ncommand failed to start: %v", runErr)
		return loop.ToolResult{Content: content, IsError: true}, nil
	default:
		return loop.ToolResult{Content: content}, nil
	}
}
